### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by brennonwilliams** [emoacht/ManagedNativeWifi#2]
Hi,
Firstly, great job putting this together - it is a lot of detailed expertise.
I downloaded the code but unfortunately, there are over 400 errors due to syntax inserts (For example: Trace.WriteLine($"{{Name: {profile.Name}");)
The "$" is not permitted in this method - Are you using some add in that has created all these issues?

Without being able to compile, I had a quick scan through and I was trying to ascertain how one would connect to a wireless SSID, and supply a password with your methods?

Thanks again.

Cheers

**Comment by emoacht** [comment]
Hi,
First, the $ headed strings are `string interpolation`, one of the new features introduced in C# 6.0. It is equivalent to `String.Format` method. You need VS 2015 or newer to handle it.

Second, regarding the way to connect a wireless network, you first need a wireless profile customized for the network. The profile includes all the information required for the connection such as SSID, password and so on. Actually the profile is represented in XML and if there were no profile for the network, you can compose it from scratch. There are samples of various profiles.

- [Wireless Profile Samples](https://msdn.microsoft.com/en-us/library/windows/desktop/aa369853.aspx)

Once you created a profile, you can set it by `SetProfile` function. Please note, as you will see, creating a profile will be quite cumbersome task. Instead, an easier solution is to first let a user to connect the network using OS's standard function so that a customized profile will be created by OS and to use that profile in your app. It depends on your app design.

Good luck!
